title: Hello! Look around to find some cool Data Science projects!
show_downloads: true
theme: jekyll-theme-cayman
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "tables"]

